---
title: "Big Classes"
author: "David Kane"
date: "3/3/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(fs)
library(gt)
library(readxl)
library(janitor)
library(tidyverse)
```


```{r download_data, include=FALSE}
# Using include=FALSE is a hack here, but I have trouble remembering how to turn
# off the annoying messages from download.file(). It is useful to give things
# sensible names, and to use those names in a consistent fashion. I have two
# enrollments to worry about: current and old. So, I use those names three
# times: the url, the new xlsx file and the R object.

url_current <- "https://registrar.fas.harvard.edu/files/fas-registrar/files/class_enrollment_summary_by_term_2.25.20_0.xlsx"
  
url_old <-  "https://registrar.fas.harvard.edu/files/fas-registrar/files/class_enrollment_summary_by_term_3.22.19_0.xlsx" 
  
download.file(url = url_current,
              destfile = "current.xlsx")

download.file(url = url_old,
              destfile = "old.xlsx")

current <- read_excel("current.xlsx", skip = 3) %>% 
  clean_names() %>% 
  filter(! is.na(course_name))
  
old <- read_excel("old.xlsx", skip = 3) %>% 
  clean_names() %>% 
  filter(! is.na(course_name)) %>% 
  select(course_id)

# Nice practice to delete the xlsx files once we no longer need them. It is not
# required that I keep them in the repo since I can (always?) download them
# anytime I want.

file_delete(c("current.xlsx", "old.xlsx"))
```

```{r}
# Bring the data together, using course_id, but only keep the courses which are
# new this year, meaning that the course_id did not exist in spring 2019. This
# lists seems much more dominated by Gen Ed courses than it normally is,
# probably because so much of the Gen Ed program was revamped this year. I think
# that these are mostly new courses. But not all of them! The Incas has
# definitely been around for several years. Did it used to be offered in the
# Fall? Did they change its course id? These are the sorts of details we would
# spend time investigating, if this were an actual project.

anti_join(current, old, by = "course_id") %>% 
  arrange(desc(total)) %>% 
  select(course_title, course_name, total) %>% 
  slice(1:5) %>% 
  gt() %>% 
    tab_header(title = "Five Largest New Harvard Courses",
               subtitle = "General Education dominates") %>% 
    tab_source_note(source_note = "Data from www.harvard.edu") %>% 
    cols_label(course_title = "Number",
               course_name = "Name",
               total = "Enrollment")
```

